Shop/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myshop.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myshop/models.py
from django.db import models
from django.contrib.auth.models import User

class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, null=True)
    phone = models.CharField(max_length=20, blank=True, null=True)
    email = models.CharField(max_length=255, blank=True, null=True)
    address = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return self.user.username if self.user else self.email

class Product(models.Model):
    name = models.CharField(max_length=200, null=True)
    price = models.IntegerField()
    image = models.ImageField(upload_to='product/images/')
    category = models.CharField(max_length=100 ,null=True)
    description = models.CharField(max_length=200, null=True)
    def __str__(self):
        return self.name

class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True , blank=True)
    products = models.ManyToManyField(Product, through='CartItem')
    # quantity = models.PositiveIntegerField(default=1)
    # created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return str(self.user )

class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f"{self.product.name} - {self.quantity}"
    
class Review(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='reviews')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rating = models.PositiveSmallIntegerField(null = True)
    comment = models.TextField(blank=True, null=True)
    image = models.ImageField(upload_to='review/',null=True,blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f'Review by {self.user.username} on {self.product.name}'

myshop/forms.py
from django import forms
from .models import *
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

class RegisterForm(forms.Form):
    username = forms.CharField(
        label='Tên Tài Khoản',
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        initial=''
    )
    email = forms.EmailField(
        label='Email',
        widget=forms.EmailInput(attrs={'class': 'form-control'}),
        initial=''
    )
    password1 = forms.CharField(
        label='Mật Khẩu',
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        initial=''
    )
    password2 = forms.CharField(
        label='Nhập Lại Mật Khẩu',
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        initial=''
    )

    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username=username).exists():
            raise ValidationError('Tên tài khoản đã được sử dụng!')
        return username

    # def clean_email(self):
    #     email = self.cleaned_data['email']
    #     if User.objects.filter(email=email).exists():
    #         raise ValidationError('Email đã được đăng ký. Vui lòng sử dụng một cái khác.')
    #     return email

    def clean(self):
        cleaned_data = super().clean()
        password1 = cleaned_data.get('password1')
        password2 = cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            error_message = 'Vui lòng nhập cùng một mật khẩu vào cả hai trường.'
            self.add_error('password2', error_message)

    def save(self):
        username = self.cleaned_data['username']
        email = self.cleaned_data['email']
        password = self.cleaned_data['password1']
        user = User.objects.create_user(username=username, email=email, password=password)
        # Tạo khách hàng mới và liên kết người dùng với khách hàng
        customer = Customer.objects.create(user=user)
        customer.name = username  # Cập nhật tên của khách hàng
        customer.save()
        return user
class LoginForm(forms.Form):
    username = forms.CharField(
        label='Tên Tài Khoản',
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        initial=''
    )
    password1 = forms.CharField(
        label='Mật Khẩu',
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        initial=''
    )

# Tìm kiếm sản phẩm 
class ProductSearchForm(forms.Form):
    search_item = forms.CharField(label="", widget=forms.TextInput(attrs={'class': 'form-control rounded-0 search-input', 'placeholder': 'Nhập tên sản phẩm'}))
    
class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ['name', 'email', 'phone', 'address']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'phone': forms.TextInput(attrs={'class': 'form-control'}),
            'address': forms.TextInput(attrs={'class': 'form-control'}),
        }
                
class ReviewForm(forms.ModelForm):
    comment = forms.CharField(widget=forms.Textarea(attrs={'class': 'review-comment'}))

    class Meta:
        model = Review
        fields = ['rating', 'comment', 'image']

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>{% block title %} Trang chủ{% endblock %}</title>
    <meta name="description" content />
    <link rel="stylesheet" href="{% static 'css/carta.css' %}">
    <link rel="stylesheet" href="{% static 'css/cards.css' %}">
    <link rel="stylesheet" href="{% static 'css/banner.css' %}">
    <link rel="stylesheet" href="{% static './css/bootstrap.min.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
        integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />

</head>

<body>
    <div class=" bg-white container-fluid d-flex justify-content-center" style="z-index: 99999;">
        <div class="bg-white position-fixed container-lg" style=" z-index: 9999">
            <header class="container-fluid">
                <div class="container-lg ">
                    <div class="row border-bottom p-1">
                        <div class="col-7 d-flex align-items-center">
                            Hai Chau Da Nang Viet Nam
                        </div>
                        <div class="col-2"></div>
                        <div class="col-3 d-flex align-items-center gap-2 justify-content-end">
                            {% if user.is_authenticated%}
                            {{customer.name}}
                            <a href="{% url 'user_profile'%}"><i class="fa-solid fa-circle-user fa-xl"
                                    style="color: #000000;"></i></a>
                            <a href="{% url 'logout' %}">Đăng xuất</a>
                            {% else %}
                            <a href="{% url 'login' %}" class="text-dark text-decoration-none">
                                <p class="m-0">Đăng Nhập</p>
                            </a>
                            <a href="{% url 'register' %}" class="text-dark text-decoration-none">
                                <p class="m-0">Đăng Ký</p>
                            </a>
                            {% endif%}
                        </div>
                    </div>
                    <div class="row bg-light">
                        <h1 class="logo col-3 d-flex align-items-center justify-content-center p-3" style="background-image: url('https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS4zgWZeN1iCZzOBwhwVOtX_4k857hMeMIbSn20oaQM2o6LSieiENsBNxWcG56o8cxMQSc&usqp=CAU');
                        background-clip:text;
                        color:transparent;
                        background-color:rgb(21, 16, 16);">
                            RYON
                        </h1>
                        <form class="col-7 d-flex align-items-center justify-content-center" method="get"
                            action="{% url 'search_results' %}">
                            {{ search_form.search_item }}
                            <button type="submit" class="btn btn-success rounded-0 h-50 w-25  ">Tìm Kiếm</button>
                        </form>
                        <!-- giỏ hàng  -->
                        <div class="col-2 d-flex align-items-center justify-content-center">
                            <a class="border-0 " href="/cart/">
                                <i class="fas fa-shopping-basket fa-2x text-success"
                                    style="transition: color 0.3s;"></i>
                            </a>
                            <p class="position-relative  text-bg-danger text-center d-flex align-items-center justify-content-center    "
                                style="border-radius: 100%;width: 20px; height: 20px; left: -10px; ">{{total_quality }}
                            </p>
                        </div>
                    </div>
                </div>
            </header>
            <nav class="container-lg bg-dark p-2 m-0" style="z-index: 9999;">
                <div class="row justify-content-around  ">
                    <div class="col-sm-8 col-lg-8 d-flex justify-content-around ">
                        <a href="/" class="text-decoration-none text-light">Trang
                            chủ </a>
                        <a href="/product/" class="text-decoration-none text-light">Sản
                            phẩm</a>
                        <a href="#" class="text-decoration-none text-light">Về chúng
                            tôi</a>
                        <a href="#" class="text-decoration-none text-light">Trợ
                            giúp</a>
                    </div>
                    <div class="col-3 d-md-block d-none text-light d-flex justify-content-center ">
                        <p class=" m-0">Hotline : 19001516</p>
                    </div>
                </div>
            </nav>
        </div>
    </div>
    <div class="bg-white " style="height: 150px;"></div>
    <div class="d-flex justify-content-center flex-column">
        {% block content %} {% endblock %}
    </div>
    <footer class="text-center d-md-block d-none container-lg text-lg-start bg-body-tertiary text-muted">
        <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
            <div class="me-5 d-none d-lg-block">
                <span>Kết nối với chúng tôi trên mạng xã hội:</span>
            </div>
            <div>
                <a href class="me-4 text-reset">
                    <i class="fab fa-facebook-f"></i>
                </a>
                <a href class="me-4 text-reset">
                    <i class="fab fa-twitter"></i>
                </a>
                <a href class="me-4 text-reset">
                    <i class="fab fa-google"></i>
                </a>
                <a href class="me-4 text-reset">
                    <i class="fab fa-instagram"></i>
                </a>
                <a href class="me-4 text-reset">
                    <i class="fab fa-linkedin"></i>
                </a>
                <a href class="me-4 text-reset">
                    <i class="fab fa-github"></i>
                </a>
            </div>
        </section>

        <section class>
            <div class="container text-center text-md-start mt-5">
                <div class="row mt-3">
                    <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
                        <h6 class="text-uppercase fw-bold mb-4">
                            <i class="fas fa-gem me-3"></i>Tên công ty
                        </h6>
                        <p>
                            Ở đây bạn có thể sử dụng hàng và cột để tổ chức
                            nội dung footer.
                            Lorem ipsum
                            dolor sit amet, consectetur adipisicing elit.
                        </p>
                    </div>

                    <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
                        <h6 class="text-uppercase fw-bold mb-4">
                            Sản phẩm
                        </h6>
                        <p>
                            <a href="#!" class="text-reset">Angular</a>
                        </p>
                        <p>
                            <a href="#!" class="text-reset">React</a>
                        </p>
                        <p>
                            <a href="#!" class="text-reset">Vue</a>
                        </p>
                        <p>
                            <a href="#!" class="text-reset">Laravel</a>
                        </p>
                    </div>

                    <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
                        <h6 class="text-uppercase fw-bold mb-4">
                            Liên kết hữu ích
                        </h6>
                        <p>
                            <a href="#!" class="text-reset">Bảng giá</a>
                        </p>
                        <p>
                            <a href="#!" class="text-reset">Cài đặt</a>
                        </p>
                        <p>
                            <a href="#!" class="text-reset">Đơn hàng</a>
                        </p>
                        <p>
                            <a href="#!" class="text-reset">Trợ giúp</a>
                        </p>
                    </div>

                    <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
                        <h6 class="text-uppercase fw-bold mb-4">Liên hệ</h6>
                        <p><i class="fas fa-home me-3"></i> New York, NY
                            10012, Hoa Kỳ</p>
                        <p>
                            <i class="fas fa-envelope me-3"></i>
                            info@example.com
                        </p>
                        <p><i class="fas fa-phone me-3"></i> + 01 234 567
                            88</p>
                        <p><i class="fas fa-print me-3"></i> + 01 234 567
                            89</p>
                    </div>
                </div>
            </div>
        </section>
    </footer>
</body>
<script src="{% static 'js/carts.js'%}"></script>


</html>

templates/cart.html
<!DOCTYPE html>
{% extends "base.html"%}
{% load static %}

{% block styles%}
<link rel="stylesheet" href="{% static 'css/banner.css' %}">
<link rel="stylesheet" href="{% static 'css/carts.css' %}">
{% endblock styles%}
{% block content%}
<div class=" banner0 container-lg  ">
    <div class="bannerinfos container-xxl d-flex">
        <i class="fa-solid fa-house fa-xxl"></i>
        <i class="fa-solid fa-chevron-right"></i>
        <h5>Giỏ hàng</h5>
    </div>
</div>
<div class="container-lg d-flex justify-content-center accordion ">
    <div class="shopping-cart border">
        <div class="shopping-cart-title d-flex justify-content-evenly b-l border">
            <b style="margin-left: 50px;">Sản phẩm</b>
            <b class="ms-5">Giá</b>
            <b style="margin-left: 50px;">Số lượng</b>
            <b></b>
        </div>
        <div class="d-flex flex-column align-items-center justify-center"
            style="position: relative; top: 50%; left: 50%; transform: translate(-50%,-50%);">
        </div>
        {% for item in items %}
        <div class="shopping-cart-items">
            <div class="shopping-cart-items-item">
                <div class="d-flex align-items-center gap-5" style="width: 240px;">
                    <img class="shopping-cart-items-img" alt=" " src="{{item.product.image.url}}">
                    <div>
                        <h3 style="width: 160px; font-size: 1rem;">{{ item.product.name }}</h3>
                    </div>
                </div>
                <h2 style="width: 100px; font-size: 1.2rem;">{{ item.product.price }}</h2>
                <div class="quantity mb-3 d-flex justify-content-between align-items-center shadow me-4">
                    <form method="POST" action="{% url 'cart_detail' %}">
                        {% csrf_token %}
                        <input type="hidden" name="product_id" value="{{ item.id }}">
                        <button class="rounded-circle shadow border-0 " type="submit" name="action" value="minus"><i
                                class="fa-solid fa-minus"></i></button>
                    </form>
                    <p class="border rounded-1  d-1 p-1 m-0 w-50 text-center ">{{ item.quantity }}</p>
                    <form method="POST" action="{% url 'cart_detail' %}">
                        {% csrf_token %}
                        <input type="hidden" name="product_id" value="{{ item.id }}">
                        <button class="rounded-circle shadow border-0 " type="submit" name="action" value="plus"><i
                                class="fa-solid fa-plus"></i></button>
                    </form>
                </div>
                <form method="POST" action="{% url 'cart_detail' %}">
                    {% csrf_token %}
                    <input type="hidden" name="product_id" value="{{ item.id }}">
                    <button class="mb-3 border-0 bg-none cart-remove" type="submit" name="action" value="delete"><i
                            class="fa-solid fa-circle-xmark fa-2xl" style="color: #ff0000;"></i>
                    </button>
                </form>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="shopping-total d-flex border">
        <div class="d-flex justify-content-between">
            <span style="font-size:1.2rem ;">Số sản phẩm : &nbsp;{{total_quality}}</span>
            <span></span>
        </div>
        <hr />
        <div class="d-flex justify-content-between">
            <span style="font-size:1.2rem ;"> Giảm giá : &nbsp;{{discount}}% </span>
            <span></span>
        </div>
        <hr />
        <div class="d-flex justify-content-between">
            <b style="font-size:1.2rem ; text-shadow: 2px 2px 0px rgba(246, 255, 0, 0.402);"
                class="text-warning  ">Thành tiền: {{ total_price }} vnd</b>
            <span></span>
        </div>
        <hr />
        {% if user.is_authenticated %}
        <button type="submit" class="order-button"> <a class="text-light text-decoration-none"
                href="{% url 'check_item' %}">Đặt
                hàng</a></button>
        {% if messages %}
        <div id="notification" class="notification rounded-2  text-danger border shadow top-50 w-25 "
            style="left: 30%;">
            {% for message in messages %}
            <b>{{ message }}</b>
            {% endfor %}
        </div>
        {% endif %}

        {% else %}
        Vui lòng đăng nhập
        {% endif %}
    </div>
</div>
<script>
    // Lấy phần tử thông báo
    var notification = document.getElementById('notification');

    // Hiển thị thông báo
    notification.style.display = 'block';

    // Ẩn thông báo sau 1 giây
    setTimeout(function () {
        notification.style.display = 'none';
    }, 1000);
</script>

{% endblock %}

templates/create_customer.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <title>{% block title %} Trang chủ{% endblock %}</title>
    <meta name="description" content />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
        integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static './css/bootstrap.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/banner.css' %}">
    <link rel="stylesheet" href="{% static './css/bootstrap.min.css' %}">


    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
        integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />

</head>

<body>
    <div class="banner0 mt-4  container-lg ">
        <div class="bannerinfos  container-xxl d-flex">
            <i class="fa-solid fa-house fa-xxl"></i>
            <i class="fa-solid fa-chevron-right"></i>
            <h5>Cập nhật thông tin </h5>
        </div>
    </div>

    <div class="container-lg d-flex justify-content-center flex-column   align-items-center">
        <h2><b>Cập nhật thông tin</b></h2>
        <div class="card w-50 container m-5 p-5 ">
            <!-- create_customer.html -->
            <form class="d-flex flex-column gap-4" method="POST" action="">
                {% csrf_token %}

                <div class="form-group">
                    <label for="id_name">Tên:</label>
                    {{ form.name }}
                </div>

                <div class="form-group">
                    <label for="id_email">Email:</label>
                    {{ form.email }}
                </div>

                <div class="form-group">
                    <label for="id_phone">Số điện thoại:</label>
                    {{ form.phone }}
                </div>

                <div class="form-group">
                    <label for="id_address">Địa chỉ:</label>
                    {{ form.address }}
                </div>

                <button type="submit" class="btn btn-primary">Cập nhật
                </button>
            </form>
        </div>
    </div>

</body>

</html>

templates/home.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}

{% block styles %}
<link rel="stylesheet" href="{% static 'css/banner.css' %}">
{% endblock styles %}

{% block content %}
<div class="banner0   container-xl mt-4 ">
    <div class="bannerinfos  container-xxl d-flex">
        <i class="fa-solid fa-house fa-xxl"></i>
        <i class="fa-solid fa-chevron-right"></i>
        <h5>Trang chủ</h5>
    </div>
</div>
<div class="banner1 container-lg">
</div>
<br>
<div class="container-lg d-flex flex-wrap  gap-2 justify-content-center ">
    {% for product in products|slice:":5" %}
    <div class="card  " style=" z-index: -9">
        <div class="" style="height: 320px;width: 100%;">
            <div class="card-image">
                <img src="{{product.image.url}}" alt="Card Image">
            </div>
            <div class="card-content">
                <h3 class="card-title">{{product.name}}</h3>
            </div>

        </div>
        <div class="d-flex  justify-content-around align-content-center align-items-center py-3 ">
            <p class=" p-0  m-0 card-description">{{product.price}}&nbsp;k</p>

            <button class="btn btn-primary w-50 justify-content-center  ">
                <a class="text-light text-decoration-none " href="{% url 'add_to_cart' product.id %}">Mua
                    ngay</a></button>
        </div>
    </div>
    {% endfor %}
</div>
<br>


<div class="d-flex justify-content-center ">
    <div class="disbanded__bg ">
        <img class="container-lg" src="../../../static/image/tim-hieu-ve-phong-cach-thoi-trang-toi-gian-2.jpg">
    </div>

</div>
<div class="d-flex justify-content-center ">
    <div class="disbanded d-flex container-lg  p-5" style="background-image: url('../static/image/banner.jpg'); height: 500px;
      background-size: cover;
      margin: 10px;background-color: #aee875; /* Màu nền bạn muốn áp dụng */
      background-blend-mode: multiply; ">
        <div class="p-5 disbanded__time rounded-1 d-flex flex-column  position-relative text-bg-light shadow text-center "
            style="left: 50%; transform: translate(-50%,0%);">
            <h3>BEST DEALS</h3>
            <h2 class="shadow">GIẢM GIÁ TRONG THÁNG </h2>
            <table class="shadow text-center">
                <tr>
                    <td>Ngày</td>
                    <td>Giờ</td>
                    <td>Phút</td>
                    <td>Giây</td>
                </tr>
                <tr>
                    <td id="days" class="time"></td>
                    <td id="hours" class="time"></td>
                    <td id="minutes" class="time"></td>
                    <td id="seconds" class="time"></td>
                </tr>
            </table>
            <button class="btn">Mua Ngay <i class="fa-solid fa-arrow-right fa-xxl"></i></button>
        </div>
    </div>
</div>


{% block scripts %}

<script>
    // Hàm chạy giờ
    function countdown(endDate) {
        // Tính toán thời gian còn lại
        const timeLeft = endDate - new Date();

        // Chuyển đổi thời gian còn lại thành ngày, giờ, phút và giây
        const days = Math.floor(timeLeft / (1000 * 60 * 60 * 24));
        const hours = Math.floor((timeLeft % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
        const minutes = Math.floor((timeLeft % (1000 * 60 * 60)) / (1000 * 60));
        const seconds = Math.floor((timeLeft % (1000 * 60)) / 1000);

        // Cập nhật giao diện người dùng với thời gian còn lại
        document.getElementById("days").innerHTML = formatNumber(days);
        document.getElementById("hours").innerHTML = formatNumber(hours);
        document.getElementById("minutes").innerHTML = formatNumber(minutes);
        document.getElementById("seconds").innerHTML = formatNumber(seconds);

        // Kiểm tra nếu thời gian còn lại đã hết
        if (timeLeft < 0) {
            document.getElementById("countdown").innerHTML = "Hết thời gian";
            // Thực hiện các hành động khác khi hết thời gian (ví dụ: ẩn nút mua hàng)
        }
    }

    // Hàm định dạng số thành chuỗi có hai chữ số (vd: 01, 02, 03)
    function formatNumber(number) {
        return number < 10 ? `${number}` : number;
    }

    // Thiết lập thời gian kết thúc (ngày, giờ, phút, giây)
    const endDate = new Date("2024-05-26T00:00:00Z");

    // Cập nhật thời gian mỗi giây
    setInterval(function () {
        countdown(endDate);
    }, 1000);
</script>
{% endblock scripts %}

{% endblock content %}

templates/user_profile.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}

{% block styles %}
<link rel="stylesheet" href="{% static 'css/banner.css' %}">
{% endblock styles %}

{% block title %}
Cập nhật thông tin
{% endblock %}

{% block content %}
<div class="banner0 mt-4  container-lg ">
    <div class="bannerinfos  container-xxl d-flex">
        <i class="fa-solid fa-house fa-xxl"></i>
        <i class="fa-solid fa-chevron-right"></i>
        <h5>Thông tin </h5>
    </div>
</div>

<div class="container p-3">
    <h1 class="text-center mb-4">Thông tin khách hàng</h1>
    <div class="customer-info w-100 d-flex justify-content-center" style="width: 1000px">
        <ul class="list-group w-75">
            <li class="list-group-item">
                <strong>Tên đăng nhập:</strong> {{ customer.name }}
            </li>
            <li class="list-group-item">
                <strong>Số điện thoại:</strong> {{ customer.phone }}
            </li>
            <li class="list-group-item">
                <strong>Địa chỉ email:</strong> {{ customer.email }}
            </li>
            <li class="list-group-item">
                <strong>Địa chỉ:</strong> {{ customer.address }}
            </li>
            <div class="text-right mt-4 d-flex justify-content-end">
                <a href="{% url 'user_detail' %}" class=""><button class="btn btn-primary">Sửa thông tin</button></a>
            </div>
        </ul>
    </div>
</div>
{% endblock %}